# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a093cc08a1062a2809be4b0c122158d0d1e47e07219e58a3740e0bec66da28803bf9dc121331180f281ca72f965151e971e097a29a562a8331da68b294ea0316

test:
  secret_key_base: 383d5f03d27ca3568114c021daeb633aa198b323420e38e60983b26251a3fae424bf5c5c2108f828e6b374fbcf02575af856d9ae63e02bbfc5a3e38c4a78721c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
